### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by gwenf** [gwenf/vue-nwjs-hours-tracking#2]
- [x] Create settings and settings form pages
- [x] Be able to enter in setting information and save
- [x] Display user setting information on settings page

**Comment by gwenf** [comment]
From Stream:
Bug with saving user settings form
Figure out why onSubmit is not being called

**Comment by alrifay** [comment]
> Figure out why onSubmit is not being called

I think you need to add `type="submit"` to the save button

https://github.com/gwenf/vue-nwjs-hours-tracking/blob/3beee302ab78e16ce9d454ba376a3a1062aba6ee/src/views/SettingsEdit.vue#L87-L89
